coverage:
  status:
    patch:
      default:
        enabled: false
    project:
       client:
       threshold: 50%
       target: 50%
        paths:
        - packages/client
        flags:
        - "client"
