rules:
  hex-length:
    - 1
    - style: long
  nesting-depth:
    - 1
    - max-depth: 4
  property-sort-order:
    - 1
    - order: concentric
  indentation: 0
  leading-zero: 0
  class-name-format: 0
  mixins-before-declarations: 0
  force-element-nesting: 0
