coverage:
  status:
    patch: off
    project:
      default: off
      client:
        target: 80%
        flags: client
      service:
        target: 70%
        flags: service
  flags:
    service:
      paths:
        - packages/service/
      carryforward: true
    client:
      paths:
        - packages/client/
      carryforward: true
