# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Merge Request PR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run lerna:bootstrap
    - run: npm run lerna:lint
    - run: npm run lerna:test
    - run: npm run lerna:build
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
       token: ${{ secrets.CODECOV_TOKEN }}
       file: ./packages/client/coverage/clover.xml
       flags: client
       name: coverage-client
      env:
        CI: true
